language: objective-c
osx_image: xcode7.2

script: 
  - xctool -project SampleApp/SampleApp.xcodeproj -scheme SampleApp build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - ( cd SampleApp ; bash <(curl -s https://codecov.io/bash) )