language: objective-c
osx_image: xcode7.2

script: 
  - xcodebuild test -project SampleApp/SampleApp.xcodeproj -scheme SampleAppTests -destination 'platform=iOS Simulator,OS=9.2,name=iPhone 6s' -sdk iphonesimulator -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)