language: objective-c
osx_image: xcode7.2

script: 
  - xctool -destination 'platform=iOS Simulator,OS=8.0,name=iPhone 6s' -project SampleApp/SampleApp.xcodeproj -scheme SampleAppTests build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)